triggers: 
 - 
   branchFilters: 
   - 
   "+master"
  pathFilters: 
  batchChanges: false
  maxConcurrentBuildsPerBranch: 1
  pollingInterval: 0
  triggerType: 2
variables: 
 "system.debug": 
  value: false
  allowOverride: true
variableGroups: 
 - 
   variables: 
   MajorVersion: 
    value: 2
   MinorVersion: 
    value: 1
   PatchVersion: 
    value: 0
  type: Vsts
  name: "Logger Variables"
  description: "Values related to the assembly/build versions and are used in all Pipelines"
  id: 1
 - 
   variables: 
   AlphaVersion: 
    value: "$(SemanticVersion)-$(Build.BuildId).Alpha"
   BetaVersion: 
    value: "$(SemanticVersion)-$(Build.BuildId).Beta"
   SemanticVersion: 
    value: "$(MajorVersion).$(MinorVersion).$(PatchVersion)"
  type: Vsts
  name: "Shared Global Variables"
  description: "Values related to the assembly/build versions and are used in all Pipelines"
  id: 3
retentionRules: 
 - 
   branches: 
   - 
   "+refs/heads/*"
  artifacts: 
  artifactTypesToDelete: 
   - 
   FilePath
   - 
   SymbolStore
  daysToKeep: 10
  minimumToKeep: 1
  deleteBuildRecord: true
  deleteTestResults: true
properties: 
tags: 
_links: 
 self: 
  href: "https://dev.azure.com/ProphetsWay/dadb23ce-840b-4b7d-9783-dc5e9a2d9029/_apis/build/Definitions/5?revision=16"
 web: 
  href: "https://dev.azure.com/ProphetsWay/dadb23ce-840b-4b7d-9783-dc5e9a2d9029/_build/definition?definitionId=5"
 editor: 
  href: "https://dev.azure.com/ProphetsWay/dadb23ce-840b-4b7d-9783-dc5e9a2d9029/_build/designer?id=5&_a=edit-build-definition"
 badge: 
  href: "https://dev.azure.com/ProphetsWay/dadb23ce-840b-4b7d-9783-dc5e9a2d9029/_apis/build/status/5"
buildNumberFormat: "$(date:yyyyMMdd)$(rev:.r) v$(MajorVersion).$(MinorVersion).$(PatchVersion)-$(Build.BuildId)"
jobAuthorizationScope: 1
jobTimeoutInMinutes: 60
jobCancelTimeoutInMinutes: 5
badgeEnabled: true
process: 
 phases: 
  - 
   steps: 
    - 
   environment: 
     enabled: false
     continueOnError: false
     alwaysRun: false
     displayName: "PowerShell Script"
     timeoutInMinutes: 0
     condition: "succeeded()"
     task: 
      id: "e213ff0f-5d5c-4791-802d-52ea3e7be1f1"
      versionSpec: "2.*"
      definitionType: task
     inputs: 
      targetType: inline
      filePath: ""
      arguments: ""
      script: "# Write your powershell commands here.\n\nWrite-Host \"Hello World\"\n\n# Use the environment variables input below to pass secret variables to this script.\n\nWrite-Host $(PackageName).$(NuGetVersion).nupkg\nWrite-Host \"$(PackageName).$(NuGetVersion).nupkg\""
      errorActionPreference: stop
      failOnStderr: false
      ignoreLASTEXITCODE: false
      pwsh: false
      workingDirectory: ""
    - 
   environment: 
     enabled: true
     continueOnError: false
     alwaysRun: false
     displayName: "Set Assembly Manifest Data"
     timeoutInMinutes: 0
     condition: "succeeded()"
     task: 
      id: "f15dc48c-4351-4c96-927c-729360a3164b"
      versionSpec: "2.*"
      definitionType: task
     inputs: 
      Path: "$(Build.SourcesDirectory)"
      FileNames: "**/ProphetsWay.Logger/ProphetsWay.Logger.csproj"
      InsertAttributes: false
      FileEncoding: auto
      WriteBOM: false
      GeneratePackageOnBuild: false
      PackageRequireLicenseAcceptance: true
      PackageId: "ProphetsWay.Logger"
      Authors: "G. Gordon Nasseri"
      Company: Prophetsway
      Product: Logger
      Description: ""
      Copyright: ""
      PackageLicenseUrl: "https://opensource.org/licenses/MIT"
      PackageProjectUrl: "https://github.com/ProphetManX/ProphetsWay.Logger/projects/1"
      PackageIconUrl: ""
      RepositoryUrl: "https://github.com/ProphetManX/ProphetsWay.Logger"
      RepositoryType: GitHub
      PackageTags: ""
      PackageReleaseNotes: ""
      Culture: ""
      VersionNumber: "$(SemanticVersion).$(Build.BuildId)"
      FileVersionNumber: "$(SemanticVersion).$(Build.BuildId)"
      InformationalVersion: "$(SemanticVersion)"
      PackageVersion: "$(SemanticVersion)"
      LogLevel: verbose
      FailOnWarning: false
      DisableTelemetry: false
      IgnoreNetFrameworkProjects: false
    - 
   environment: 
     enabled: false
     continueOnError: false
     alwaysRun: false
     displayName: "Stage Source - GitHub"
     timeoutInMinutes: 0
     condition: "succeeded()"
     task: 
      id: "5bfb729a-a7c8-4a78-a7c3-8d717bb7c13c"
      versionSpec: "2.*"
      definitionType: task
     inputs: 
      SourceFolder: "ProphetsWay.Logger"
      Contents: "**"
      TargetFolder: "$(Build.ArtifactStagingDirectory)\\github"
      CleanTargetFolder: true
      OverWrite: false
      flattenFolders: false
      preserveTimestamp: false
    - 
   environment: 
     enabled: true
     continueOnError: false
     alwaysRun: false
     displayName: "dotnet build"
     timeoutInMinutes: 0
     condition: "succeeded()"
     task: 
      id: "5541a522-603c-47ad-91fc-a4b1d163081b"
      versionSpec: "2.*"
      definitionType: task
     inputs: 
      command: build
      publishWebProjects: true
      projects: ""
      custom: ""
      arguments: ""
      restoreArguments: ""
      publishTestResults: true
      testRunTitle: ""
      zipAfterPublish: true
      modifyOutputPath: true
      selectOrConfig: select
      feedRestore: ""
      includeNuGetOrg: true
      nugetConfigPath: ""
      externalEndpoints: ""
      noCache: false
      packagesDirectory: ""
      verbosityRestore: Detailed
      searchPatternPush: "$(Build.ArtifactStagingDirectory)/*.nupkg"
      nuGetFeedType: internal
      feedPublish: ""
      publishPackageMetadata: true
      externalEndpoint: ""
      searchPatternPack: "**/*.csproj"
      configurationToPack: "$(BuildConfiguration)"
      outputDir: "$(Build.ArtifactStagingDirectory)"
      nobuild: false
      includesymbols: false
      includesource: false
      versioningScheme: off
      versionEnvVar: ""
      requestedMajorVersion: 1
      requestedMinorVersion: 0
      requestedPatchVersion: 0
      buildProperties: ""
      verbosityPack: Detailed
      workingDirectory: ""
    - 
   environment: 
     enabled: true
     continueOnError: false
     alwaysRun: false
     displayName: "VsTest - testAssemblies"
     timeoutInMinutes: 0
     condition: "succeeded()"
     task: 
      id: "ef087383-ee5e-42c7-9a53-ab56c98420f9"
      versionSpec: "2.*"
      definitionType: task
     inputs: 
      testSelector: testAssemblies
      testAssemblyVer2: "**\\*test*.dll\n!**\\*TestAdapter.dll\n!**\\obj\\**"
      testPlan: ""
      testSuite: ""
      testConfiguration: ""
      tcmTestRun: "$(test.RunId)"
      searchFolder: "$(System.DefaultWorkingDirectory)"
      resultsFolder: "$(Agent.TempDirectory)\\TestResults"
      testFiltercriteria: ""
      runOnlyImpactedTests: False
      runAllTestsAfterXBuilds: 50
      uiTests: false
      vstestLocationMethod: version
      vsTestVersion: latest
      vstestLocation: ""
      runSettingsFile: ""
      overrideTestrunParameters: ""
      pathtoCustomTestAdapters: ""
      runInParallel: False
      runTestsInIsolation: False
      codeCoverageEnabled: False
      otherConsoleOptions: ""
      distributionBatchType: basedOnTestCases
      batchingBasedOnAgentsOption: autoBatchSize
      customBatchSizeValue: 10
      batchingBasedOnExecutionTimeOption: autoBatchSize
      customRunTimePerBatchValue: 60
      dontDistribute: False
      testRunTitle: ""
      platform: ""
      configuration: ""
      publishRunAttachments: true
      failOnMinTestsNotRun: False
      minimumExpectedTests: 1
      diagnosticsEnabled: True
      collectDumpOn: onAbortOnly
      rerunFailedTests: False
      rerunType: basedOnTestFailurePercentage
      rerunFailedThreshold: 30
      rerunFailedTestCasesMaxLimit: 5
      rerunMaxAttempts: 3
    - 
   environment: 
     enabled: true
     continueOnError: false
     alwaysRun: false
     displayName: "Pack and Stage Alpha NuGet Package"
     timeoutInMinutes: 0
     condition: "succeeded()"
     task: 
      id: "5541a522-603c-47ad-91fc-a4b1d163081b"
      versionSpec: "2.*"
      definitionType: task
     inputs: 
      command: pack
      publishWebProjects: true
      projects: ""
      custom: ""
      arguments: "-o $(Build.ArtifactStagingDirectory)\\build"
      restoreArguments: ""
      publishTestResults: true
      testRunTitle: ""
      zipAfterPublish: true
      modifyOutputPath: true
      selectOrConfig: select
      feedRestore: ""
      includeNuGetOrg: true
      nugetConfigPath: ""
      externalEndpoints: ""
      noCache: false
      packagesDirectory: ""
      verbosityRestore: Detailed
      searchPatternPush: "$(Build.ArtifactStagingDirectory)/*.nupkg"
      nuGetFeedType: internal
      feedPublish: ""
      publishPackageMetadata: true
      externalEndpoint: ""
      searchPatternPack: "ProphetsWay.Logger/ProphetsWay.Logger.csproj"
      configurationToPack: "$(BuildConfiguration)"
      outputDir: "$(Build.ArtifactStagingDirectory)\\alpha"
      nobuild: false
      includesymbols: false
      includesource: false
      versioningScheme: byEnvVar
      versionEnvVar: AlphaVersion
      requestedMajorVersion: 0
      requestedMinorVersion: 0
      requestedPatchVersion: 0
      buildProperties: ""
      verbosityPack: Detailed
      workingDirectory: ""
    - 
   environment: 
     enabled: true
     continueOnError: false
     alwaysRun: false
     displayName: "Pack and Stage Beta NuGet Package"
     timeoutInMinutes: 0
     condition: "succeeded()"
     task: 
      id: "5541a522-603c-47ad-91fc-a4b1d163081b"
      versionSpec: "2.*"
      definitionType: task
     inputs: 
      command: pack
      publishWebProjects: true
      projects: ""
      custom: ""
      arguments: "-o $(Build.ArtifactStagingDirectory)\\build"
      restoreArguments: ""
      publishTestResults: true
      testRunTitle: ""
      zipAfterPublish: true
      modifyOutputPath: true
      selectOrConfig: select
      feedRestore: ""
      includeNuGetOrg: true
      nugetConfigPath: ""
      externalEndpoints: ""
      noCache: false
      packagesDirectory: ""
      verbosityRestore: Detailed
      searchPatternPush: "$(Build.ArtifactStagingDirectory)/*.nupkg"
      nuGetFeedType: internal
      feedPublish: ""
      publishPackageMetadata: true
      externalEndpoint: ""
      searchPatternPack: "ProphetsWay.Logger/ProphetsWay.Logger.csproj"
      configurationToPack: "$(BuildConfiguration)"
      outputDir: "$(Build.ArtifactStagingDirectory)\\beta"
      nobuild: false
      includesymbols: false
      includesource: false
      versioningScheme: byEnvVar
      versionEnvVar: BetaVersion
      requestedMajorVersion: 0
      requestedMinorVersion: 0
      requestedPatchVersion: 0
      buildProperties: ""
      verbosityPack: Detailed
      workingDirectory: ""
    - 
   environment: 
     enabled: true
     continueOnError: false
     alwaysRun: false
     displayName: "Pack and Stage Final NuGet Package"
     timeoutInMinutes: 0
     condition: "succeeded()"
     task: 
      id: "5541a522-603c-47ad-91fc-a4b1d163081b"
      versionSpec: "2.*"
      definitionType: task
     inputs: 
      command: pack
      publishWebProjects: true
      projects: ""
      custom: ""
      arguments: "-o $(Build.ArtifactStagingDirectory)\\build"
      restoreArguments: ""
      publishTestResults: true
      testRunTitle: ""
      zipAfterPublish: true
      modifyOutputPath: true
      selectOrConfig: select
      feedRestore: ""
      includeNuGetOrg: true
      nugetConfigPath: ""
      externalEndpoints: ""
      noCache: false
      packagesDirectory: ""
      verbosityRestore: Detailed
      searchPatternPush: "$(Build.ArtifactStagingDirectory)/*.nupkg"
      nuGetFeedType: internal
      feedPublish: ""
      publishPackageMetadata: true
      externalEndpoint: ""
      searchPatternPack: "ProphetsWay.Logger/ProphetsWay.Logger.csproj"
      configurationToPack: "$(BuildConfiguration)"
      outputDir: "$(Build.ArtifactStagingDirectory)\\release"
      nobuild: false
      includesymbols: false
      includesource: false
      versioningScheme: byEnvVar
      versionEnvVar: SemanticVersion
      requestedMajorVersion: 0
      requestedMinorVersion: 0
      requestedPatchVersion: 0
      buildProperties: ""
      verbosityPack: Detailed
      workingDirectory: ""
    - 
   environment: 
     enabled: true
     continueOnError: false
     alwaysRun: false
     displayName: "Stage CHANGELOG.md"
     timeoutInMinutes: 0
     condition: "succeeded()"
     task: 
      id: "5bfb729a-a7c8-4a78-a7c3-8d717bb7c13c"
      versionSpec: "2.*"
      definitionType: task
     inputs: 
      SourceFolder: ""
      Contents: "CHANGELOG.md"
      TargetFolder: "$(Build.ArtifactStagingDirectory)\\"
      CleanTargetFolder: false
      OverWrite: false
      flattenFolders: false
      preserveTimestamp: false
    - 
   environment: 
     enabled: true
     continueOnError: false
     alwaysRun: false
     displayName: "Publish Artifact: drop"
     timeoutInMinutes: 0
     condition: "succeeded()"
     task: 
      id: "2ff763a7-ce83-4e1f-bc89-0ae63477cebe"
      versionSpec: "1.*"
      definitionType: task
     inputs: 
      PathtoPublish: "$(Build.ArtifactStagingDirectory)"
      ArtifactName: drop
      ArtifactType: Container
      TargetPath: ""
      Parallel: false
      ParallelCount: 8
      FileCopyOptions: ""
   name: "Agent job 1"
   refName: Job_1
   condition: "succeeded()"
   target: 
    executionOptions: 
     type: 0
    allowScriptsAuthAccessOption: false
    type: 1
   jobAuthorizationScope: 1
 type: 1
repository: 
 properties: 
  apiUrl: "https://api.github.com/repos/ProphetManX/ProphetsWay.Logger"
  branchesUrl: "https://api.github.com/repos/ProphetManX/ProphetsWay.Logger/branches"
  cloneUrl: "https://github.com/ProphetManX/ProphetsWay.Logger.git"
  connectedServiceId: "7dac2a80-dd5c-43c7-8f1e-dff7a4181fd5"
  defaultBranch: master
  fullName: "ProphetManX/ProphetsWay.Logger"
  hasAdminPermissions: True
  isFork: False
  isPrivate: False
  lastUpdated: "04/21/2019 17:10:43"
  manageUrl: "https://github.com/ProphetManX/ProphetsWay.Logger"
  nodeId: "MDEwOlJlcG9zaXRvcnkxNzQwNDc4MzI="
  ownerId: 35438914
  orgName: ProphetManX
  refsUrl: "https://api.github.com/repos/ProphetManX/ProphetsWay.Logger/git/refs"
  safeRepository: "ProphetManX/ProphetsWay.Logger"
  shortName: "ProphetsWay.Logger"
  ownerAvatarUrl: "https://avatars2.githubusercontent.com/u/35438914?v=4"
  archived: False
  externalId: 174047832
  ownerIsAUser: True
  checkoutNestedSubmodules: false
  cleanOptions: 0
  fetchDepth: 0
  gitLfsSupport: false
  reportBuildStatus: true
  skipSyncSource: false
  labelSourcesFormat: "$(build.buildNumber)"
  labelSources: 0
 id: "ProphetManX/ProphetsWay.Logger"
 type: GitHub
 name: "ProphetManX/ProphetsWay.Logger"
 url: "https://github.com/ProphetManX/ProphetsWay.Logger.git"
 defaultBranch: master
 clean: true
 checkoutSubmodules: false
processParameters: 
quality: 1
authoredBy: 
 displayName: "G. Gordon Nasseri"
 url: "https://spsprodcus1.vssps.visualstudio.com/A1c538639-ebcf-4581-b172-f2273b31edd1/_apis/Identities/0ec37c4d-748f-4edc-a2f4-119da4766c39"
 _links: 
  avatar: 
   href: "https://dev.azure.com/ProphetsWay/_apis/GraphProfile/MemberAvatars/msa.ZTFkZjlmZmItODJlYi03MWY2LThjNGMtODExYWFhMDAxY2Qz"
 id: "0ec37c4d-748f-4edc-a2f4-119da4766c39"
 uniqueName: "ProphetManX@gmail.com"
 imageUrl: "https://dev.azure.com/ProphetsWay/_apis/GraphProfile/MemberAvatars/msa.ZTFkZjlmZmItODJlYi03MWY2LThjNGMtODExYWFhMDAxY2Qz"
 descriptor: "msa.ZTFkZjlmZmItODJlYi03MWY2LThjNGMtODExYWFhMDAxY2Qz"
drafts: 
queue: 
 _links: 
  self: 
   href: "https://dev.azure.com/ProphetsWay/_apis/build/Queues/17"
 id: 17
 name: "Hosted VS2017"
 url: "https://dev.azure.com/ProphetsWay/_apis/build/Queues/17"
 pool: 
  id: 3
  name: "Hosted VS2017"
  isHosted: true
id: 5
name: "Logger CI"
url: "https://dev.azure.com/ProphetsWay/dadb23ce-840b-4b7d-9783-dc5e9a2d9029/_apis/build/Definitions/5?revision=16"
uri: "vstfs:///Build/Definition/5"
path: "\\Logger"
type: 2
queueStatus: 0
revision: 16
createdDate: "2020-06-03T00:05:03.267Z"
project: 
 id: "dadb23ce-840b-4b7d-9783-dc5e9a2d9029"
 name: "ProphetsWay GitHub Projects"
 description: "My single project in DevOps for all the projects I have hosted in GitHub"
 url: "https://dev.azure.com/ProphetsWay/_apis/projects/dadb23ce-840b-4b7d-9783-dc5e9a2d9029"
 state: 1
 revision: 28
 visibility: 2
 lastUpdateTime: "2019-03-23T03:52:56.780Z"