# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

variables:
  MajorVersion: '1'
  MinorVersion: '0'
  PatchVersion: '0'
  SemanticVersion: '$(MajorVersion).$(MinorVersion).$(PatchVersion)'
  AlphaVersion: '$(SemanticVersion)-$(Build.BuildId).Alpha'
  BetaVersion: '$(SemanticVersion)-$(Build.BuildId).Beta'
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  vmImage: 'windows-latest'


jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImage)

    steps:
    - task: Assembly-Info-NetCore@2
      inputs:
        Path: '$(Build.SourcesDirectory)'
        FileNames: '**/ProphetsWay.Hasher.csproj'
        InsertAttributes: true
        FileEncoding: 'auto'
        WriteBOM: false
        PackageRequireLicenseAcceptance: true
        PackageId: 'ProphetsWay.Hasher'
        Authors: 'G. Gordon Nasseri'
        Company: 'ProphetsWay'
        Product: 'Hasher'
        Description: 'Simple hashing library to make it easier to generate file checksums.'
        PackageLicenseUrl: 'https://opensource.org/licenses/MIT'
        RepositoryUrl: 'https://github.com/ProphetManX/ProphetsWay.Hasher'
        RepositoryType: 'GitHub'
        VersionNumber: '$(SemanticVersion).$(Build.BuildId)'
        FileVersionNumber: '$(SemanticVersion).$(Build.BuildId)'
        InformationalVersion: '$(SemanticVersion)'
        PackageVersion: '$(SemanticVersion)'
        LogLevel: 'verbose'
        FailOnWarning: false
        DisableTelemetry: false

    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'

    - task: VSTest@2
      inputs:
        testSelector: 'testAssemblies'
        testAssemblyVer2: |
          **\*test*.dll
          !**\*TestAdapter.dll
          !**\obj\**
        searchFolder: '$(System.DefaultWorkingDirectory)'
        diagnosticsEnabled: true

    - task: DotNetCoreCLI@2
      inputs:
        command: 'pack'
        packagesToPack: 'ProphetsWay.Hasher/ProphetsWay.Hasher.csproj'
        packDirectory: '$(Build.ArtifactStagingDirectory)\alpha'
        versioningScheme: 'byEnvVar'
        versionEnvVar: 'AlphaVersion'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'pack'
        packagesToPack: 'ProphetsWay.Hasher/ProphetsWay.Hasher.csproj'
        packDirectory: '$(Build.ArtifactStagingDirectory)\beta'
        versioningScheme: 'byEnvVar'
        versionEnvVar: 'BetaVersion'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'pack'
        packagesToPack: 'ProphetsWay.Hasher/ProphetsWay.Hasher.csproj'
        packDirectory: '$(Build.ArtifactStagingDirectory)\release'
        versioningScheme: 'byEnvVar'
        versionEnvVar: 'SemanticVersion'

    - task: CopyFiles@2
      inputs:
        Contents: 'CHANGELOG.md'
        TargetFolder: '$(Build.ArtifactStagingDirectory)\'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'


