parameters:
  vmImage: 'windows-latest'
  
jobs:
  - job: Build
    displayName: Build
    continueOnError: "true"
    pool: 
      vmImage: ${{parameters.vmImage}}
    steps:
      - task: DotNetCoreCLI@2
        displayName: 'Build Solution'
        inputs:
          command: 'build'

      - task: VSTest@2
        displayName: 'Run Unit Tests'
        inputs:
          testSelector: 'testAssemblies'
          testAssemblyVer2: |
            **\*test*.dll
            !**\*TestAdapter.dll
            !**\obj\**
          searchFolder: '$(System.DefaultWorkingDirectory)'
          diagnosticsEnabled: true
